# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types: [opened, sychonize, edited, reopened]
    
jobs:
  lets-do-this:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup our friend node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Buildish stuff
      run: |
       echo at sha ${{ github.event.pull_request.head.sha }}
       mkdir -p dist/${{ github.event.pull_request.number }}
       cp src/* dist/${{ github.event.pull_request.number }}
       cd dist/${{ github.event.pull_request.number }}
       mv ohcakes.html index.html
       pwd
       ls
       
    - name: Deploy OH BOY
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
